name: "Deploy Image to DockerHub"

on:
  push:
    branches:
      - master

env:
  PLATFORMS: linux/arm64/v8,linux/amd64

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - httpd-version: 2.4

    steps:
      - name: "Checkout Sourcecode"
        uses: actions/checkout@v4

      - name: "Set up Docker Buildx"
        id: builder
        uses: docker/setup-buildx-action@v3

      - name: "Append ARM buildx builder from AWS"
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: "ssh://ec2-user@arm.d.cron.eu"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Cache Docker layers"
        uses: actions/cache@v2
        with:
          path: .buildx-cache
          key: ${{ runner.os }}-buildx-${{ matrix.httpd-version }}-${{ github.sha }}
          restore-keys: |
            "${{ runner.os }}-buildx-${{ matrix.httpd-version }}-"
            "${{ runner.os }}-buildx-"

      - name: "Docker build httpd-${{ matrix.httpd-version }}"
        run: make build HTTPD_VERSION=${{ matrix.httpd-version }}

      - name: "Login to DockerHub"
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Docker build and push"
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: "croneu/phpapp-web:apache-${{ matrix.httpd-version }}"
          platforms: ${{ env.PLATFORMS }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: "Update Docker Hub Description (croneu/phpapp-web)"
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: croneu/phpapp-web
          short-description: ${{ github.event.repository.description }}
